// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/encador/trady/internal/models"

func LoginForm(data models.UserData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form action=\"/user/new\" method=\"post\"><label for=\"name\">Username</label> <input placeholder=\"Enter Name\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.Username)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/component/users.templ`, Line: 8, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" type=\"text\" id=\"name\" name=\"username\"> <label for=\"password\">Password</label> <input placeholder=\"Enter Password\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.Password)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/component/users.templ`, Line: 10, Col: 59}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" type=\"password\" name=\"password1\"> <label for=\"password\">Repeat Password</label> <input placeholder=\"Repeat Password\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(data.Password)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/component/users.templ`, Line: 12, Col: 60}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" type=\"password\" name=\"password2\"> <input type=\"submit\" id=\"submit\" value=\"Submit\"></form><style>\n\t\tform {\n\t\t\t/* border: var(--white-3) solid 3px; */\n      background-color: var(--dark-3);\n\t\t\tcolor: var(--blue-1);\n\t\t\tpadding: 20px 0px 20px 0px;\n\t\t\twidth: 250px;\n      /* min-height: 300px; */\n\t\t\theight: auto;\n\t\t\tborder-radius: 5px;\n\t\t\tdisplay: flex;\n\t\t\tflex-direction: column;\n\t\t\tjustify-content: center;\n\t\t\talign-items: center;\n\t\t}\n\t\t#submit {\n\t\t\tborder: var(--green-2) solid 3px;\n\t\t\tcolor: var(--green-1);\n\t\t\tborder-radius: 8px;\n\t\t\tbackground: none;\n\t\t\tfont-weight: bolder;\n\t\t\tmargin: 0px;\n\t\t\theight: 30px;\n\t\t\twidth: 100px;\n\t\t\tfont-size: 15px;\n\t\t}\n\t\t#submit:hover {\n\t\t\tbackground: var(--green-2);\n\t\t\tborder: var(--green-3) solid 3px;\n\t\t\tcursor: pointer;\n\t\t}\n\t\tinput {\n\t\t\tborder: var(--dark-2) solid 2px;\n\t\t\tbackground-color: var(--dark-2);\n\t\t\tcolor: var(--white-2);\n\t\t\t/* caret-color: var(--white-1); */\n\t\t\tborder-radius: 10px;\n\t\t\tpadding: 2px;\n\t\t\toutline: none;\n\t\t\tfont-size: 15px;\n\t\t\ttext-align: center;\n\t\t\twidth: 70%;\n\t\t\theight: auto;\n\t\t\tfont-weight: 500;\n\t\t\tmargin-bottom: 15px;\n\t\t}\n\t\tinput:hover {\n\t\t\tborder: var(--blue-2) dashed 2px;\n\t\t\tcursor: pointer;\n\t\t}\n\t\tinput:focus {\n\t\t\tborder: var(--blue-2) solid 2px;\n\t\t}\n\t\tlabel {\n\t\t\tborder: #00000040 dotted 2px;\n\t\t\tbackground-color: #00000005;\n\t\t\tborder-radius: 5px;\n\t\t\tborder-bottom: none;\n\t\t\twidth: fit-content;\n\t\t\ttext-align: center;\n\t\t\tpadding: 0 5px 0 5px;\n\t\t\tfont-weight: 600;\n\t\t}\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
